##services:
##  db:
##    image: postgres:14.3
##    restart: always
##    ports:
##      - "5435:5435"
##    environment:
##      POSTGRES_PASSWORD: ${DB_PASSWORD}
##      POSTGRES_DB: ${DB_NAME}
##      POSTGRES_PORT: ${POSTGRES_PORT}
##    container_name: Practica04
##    volumes:
##      - ./postgres-data:/var/lib/postgresql/data
